### ISSUE TITLE
Coudn't run configuration with ./scripts/docker.sh dv --force 

### ISSUE THREAD

**Issue by olegogogo** [ZilantRobotics/innopolis_vtol_dynamics#52]
### Command line:

>(sim-pix4) user@user-HP-ProBook-430-G7:~/projects/innopolis_vtol_dynamics$ sudo ./scripts/docker.sh dv --force # dq is abbreviation of dronecan_vtol

### Error was raised

>/dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_0668FF545151717867185839-if02
>Docker Dronecan HITL settings:
>- IMAGE_NAME is ponomarevda/uavcan_hitl_dynamics_simulator:v0.5.0amd64
>- DRONECAN_DEV_PATH_SYMLINK is /dev/serial/by-id/usb-STMicroelectronics_STM32_STLink_0668FF545151717867185839-if02
>WARNING: Package(s) not found: autopilot_tools
>configure.sh ERROR (line 95): autopilot-tools is not installed!

### But  autopilot_tools are installed in venv

> (sim-pix4) user@user-HP-ProBook-430-G7:~/projects/innopolis_vtol_dynamics$ pip list
> Package            Version
> ------------------ -----------
> autopilot-tools    0.4.2
> certifi            2024.2.2
> charset-normalizer 3.3.2
> contourpy          1.2.0
> cycler             0.12.1
> exceptiongroup     1.2.0
> fonttools          4.49.0
> future             1.0.0
> idna               3.6
> iniconfig          2.0.0
> kiwisolver         1.4.5
> lxml               5.1.0
> matplotlib         3.8.3
> numpy              1.26.4
> packaging          24.0
> pillow             10.2.0
> pip                22.0.2
> pluggy             1.4.0
> pymavlink          2.4.41
> pyparsing          3.1.2
> pyserial           3.5
> pytest             8.1.1
> python-dateutil    2.9.0.post0
> PyYAML             6.0.1
> requests           2.31.0
> setuptools         59.6.0
> six                1.16.0
> StrEnum            0.4.15
> tomli              2.0.1
> tqdm               4.66.2
> urllib3            2.2.1

**Comment by PonomarevDA** [comment]
There is definitely something wrong with your python environment. Different versions of python or something else.
