### ISSUE TITLE
PX4 parameters cannot be written in --force mode

### ISSUE THREAD

**Issue by olegogogo** [ZilantRobotics/innopolis_vtol_dynamics#66]
When i am using --force mode via:
```
./scripts/docker.sh cq  --force
```

some parameters cannot be written. Example is on image below:

![изображение](https://github.com/user-attachments/assets/adcb6b00-9425-45fb-a7c1-a1cfa8f46017)

and another example here:

![изображение](https://github.com/user-attachments/assets/f1b7db30-5397-47e9-8b12-e06bb43395bf)

looks like execution time is summing up to timeout(1.0sec) and this is causing fail

**Comment by PonomarevDA** [comment]
The bug was fixed in autopilot-tools==0.4.7 (#67). Please, try the new version.
